VEHICLES = [
    'dr.1 fighter',
    'airship l30',
    'rumpler c.i attack plane',
    'mc 3.5hp sidecar',
    'st chamond',
    'artillery truck',
    'horse',
    'mc 18j sidecar',
    'kft scout',
    'mark v landship',
    'fortress gun',
    'halberstadt cl. ii attack plane',
    'char 2c',
    'sopwith camel fighter',
    'fk 96 field gun',
    'albatros diii  fighter',
    '37/95 scout',
    'romfell armored car',
    'f.t. armored car',
    'a.e.f 2-a2 attack plane',
    'spad s xiii fighter',
    'rnas armored car',
    'heavy machine gun',
    'dreadnought',
    'gotha g.iv bomber',
    'm30 scout',
    'qf 1 aa',
    'a7v heavy tank',
    'ev4 armored car',
    'm.a.s. torpedo boat',
    'ft-17 light tank',
    'bl 9.2 siege gun',
    'caproni ca.5 bomber',
    'bristol f2.b attack plane',
    'armored train',
    'he auto-cannon'
]