WEAPONS = [
    'p08 pistol',
    'huot automatic low weight',
    'mg 08/15',
    'm1907 sl trench',
    'anti-tank mine',
    'cavalry sword',
    'smle mkiii infantry',
    'lebel model 1886 infantry',
    'lewis gun low weight',
    'gewehr 98 marksman',
    'anti-tank grenade',
    '1903 hammerless',
    'hellfighter m1911',
    'bartek bludgeon',
    'trench fleur',
    'c93',
    'doughboy m1911',
    'kukri',
    'bar m1918 trench',
    'm1911 extended',
    'trench periscope',
    'rsc 1917 factory',
    'sniper decoy',
    'm1909 benet mercie Optical',
    'autoloading 8 .35 marksman',
    'survival knife',
    'modello 1915',
    'm97 trench gun hunter',
    'frommer stop',
    'madsen mg trench',
    'bayonet charge',
    'kolibri',
    'repair tool',
    'light anti-tank grenade',
    'lebel model 1886 sniper',
    'chauchat low weight',
    'mini grenade',
    'm1907 sl factory',
    'bedouin dagger',
    'mp 18 experimental',
    'selbstlader 1906 factory',
    '12g automatic backbored',
    "lawrence of arabia's SMLE",
    'gewehr 98',
    'mars automatic',
    'howdah pistol sweeper',
    'billhook',
    'sawed off shotgun',
    'bodeo 1889',
    'cei-rigotti trench',
    'mp 18 optical',
    'automatico m1918 storm',
    'mortar he',
    'bull dog revolver',
    'medical crate',
    'hatchet',
    'mortar air',
    'ammo pouch',
    'automatico m1918 trench',
    'gas grenade',
    'model 10-a factory',
    'russian 1895 trench',
    'm1903',
    'tripwire bomb INC',
    'cei-rigotti optical',
    'gewehr m.95 marksman',
    'us trench knife',
    'selbstlader m1916 factory',
    'm1903 marksman',
    'gasser m1870',
    'lebel model 1886',
    'chauchat telescopic',
    'lewis gun suppressive',
    'lewis gun optical',
    'm97 trench gun sweeper',
    'mondragon storm',
    'incendiary grenade',
    'rifle grenade — HE',
    'c96',
    'bandage pouch',
    '12g automatic hunter',
    'k bullets',
    'tripwire bomb — GAS',
    'mp 18 trench',
    'ribeyrolles 1918 factory',
    'm1909 benet mercie Storm',
    'gewehr 98 sniper',
    'nail knife',
    'smle mkiii',
    'crossbow launcher FRG',
    'combat knife',
    'mondragon optical',
    'dynamite',
    'compact trench knife',
    'shovel',
    'tripwire bomb — HE',
    'club',
    'madsen mg low weight',
    'no. 3 revolver',
    'crossbow launcher HE',
    'raider club',
    'martini-henry',
    'limpet charge',
    'impact grenade',
    'jambiya knife',
    'flare gun spot',
    'cei-rigotti factory',
    'rsc 1917 optical',
    'trench mace',
    'mondragonn sniper',
    "red baron's p08",
    'repetierpistole m1912',
    'villar perosa',
    'model 10-a slug',
    'hellfighter trench shotgun',
    'm97 trench gun backbored',
    'russian 1895 infantry',
    'gewehr m.95 carbine',
    'mle 1903',
    'spiked club',
    '12g automatic extended',
    'smoke grenade',
    'automatico m1918 factory',
    'sniper shield',
    'madsen mg storm',
    'smle mkiii marksman',
    'gewehr 98 infantry',
    'pieper m1893',
    'selbstlader m1916 marksman',
    'hellfighter bolo knife',
    'howdah pistol',
    'saber',
    'mg15 n.a. storm',
    'trench knife',
    'mg15 n.a. suppressive',
    'c96 carbine',
    'm1907 sl sweeper',
    'm1903 sniper',
    'bar m1918 telescopic',
    'gewehr m.95',
    'pickaxe',
    'smle mkiii carbine',
    'm1911',
    'at rocket gun',
    'selbstlader m1916 optical',
    'sawtooth knife',
    'm1909 benet mercie Telescopic',
    'ammo crate',
    'autoloading 8 .35 factory',
    'sjogren inertial factory',
    'hellriegel 1915 factory',
    'mg15 n.a. low weight',
    'rifle grenade FRG',
    'bar m1918 storm',
    'cogwheel club',
    'mle 1903 extended',
    'model 10-a hunter',
    'russian 1895',
    'frommer stop auto',
    'wex',
    'rifle grenade SMK',
    'frag grenade',
    'taschenpistole m1914',
    'barbed wire bat',
    'tankgewehr m1918',
    'medical syringe',
    'autoloading 8 .25 extended',
    'martini-henry infantry',
    'flare gun flash',
    'p08 artillerie',
    'm1903 experimental',
    'auto revolver',
    'gewehr m.95 infantry',
    'russian 1895 sniper'
]